spring:
  application:
    name: game-service
  datasource:
    url: jdbc:mysql://localhost:3306/game_service_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql



mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl