server:
  port: 8081


spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/quiz_service_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

