spring:
  application:
    name: session-service

  datasource:
    url: jdbc:mysql://localhost:3306/session_service_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
